### ISSUE TITLE
Validator does not use options provided on creation

### ISSUE THREAD

**Issue by AlexMinaev19** [pb33f/libopenapi-validator#144]
### Problem I need to solve
I need to validate an email address using `format: email` (according to [OpenAPI 3.0 spec](https://swagger.io/docs/specification/v3_0/data-models/data-types/)) that is also supported by the underlying library [santhosh-tekuri/jsonschema](https://github.com/santhosh-tekuri/jsonschema).

### Possible solution
When I create a validator, I can pass options that include format checking
```go
import (
    "github.com/pb33f/libopenapi-validator/config"
    "github.com/pb33f/libopenapi"

    openAPIValidator "github.com/pb33f/libopenapi-validator"
)

...

doc, docErrs := libopenapi.NewDocument(spec)
if docErrs != nil {
    panic(docErrs)
}

validator, validatorErrs := openAPIValidator.NewValidator(doc, config.WithFormatAssertions())
if validatorErrs != nil {
    panic(validatorErrs)
}

...
```

### Issue
Unfortunately, when I try to validate a request body that has the following specification:
```yaml
components:
    schemas:
        V1_UserRequest:
            type: object
            properties:
                email:
                    type: string
                    format: email
                    minLength: 1
                    maxLength: 320
```
Validator does not check a validity of the value according to format.

### Root of the issue
A small investigation showed me that when the library tries to validate the request schema using [santhosh-tekuri/jsonschema](https://github.com/santhosh-tekuri/jsonschema) package, the validator forgets to pass the options to it and just creates new options.

```go
// file github.com/pb33f/libopenapi-validator/request/validate_body.go

...

// line 113 of ValidateRequestBodyWithPathItem method
validationSucceeded, validationErrors := ValidateRequestSchema(request, schema, renderedInline, renderedJSON, config.WithRegexEngine(v.options.RegexEngine)) // instead of passing current options, it creates a new one with only regex engine and ignores other configs
```

### Solving issue 
To solve an issue, we have to respect all validator's options and pass them to `ValidateRequestSchema` function.
