### ISSUE TITLE
Validating Path Parameters with Regex

### ISSUE THREAD

**Issue by Sakdow** [pb33f/libopenapi-validator#43]
In the context of the following YAML code snippet from the OpenAPI specification:

```yml
/companies/{company_id}:
  patch:
    summary: Update a company
    operationId: UpdateCompany
    tags:
      - Companies
    parameters:
      - name: company_id
        in: path
        required: true
        example: 9de0691c-bc8d-409b-8f40-75d4f45db2f3
        schema:
          type: string
          pattern: '/^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$/i'
          description: Unique identifier generated by the server.
```

I am attempting to validate the company_id path parameter using a regular expression. However, despite my efforts, it seems that the validation is not working as expected.

```Go
func (v Spec) ValidateRequest(request *http.Request) error {
	valid, errs := v.validator.ValidateHttpRequest(request)
	if len(errs) > 0 {
		for _, err := range errs {
			fmt.Println(err)
		}
	}

	if !valid {
		return fmt.Errorf("request is not valid")
	}

	return nil
}
```

Or with : 
```Go
func (v Spec) FindRoute(request *http.Request) error {
	_, errs, _ := paths.FindPath(request, v.document)
	if len(errs) > 0 {
		return fmt.Errorf("request is not valid : %v", errs)
	}

	valid, errs := v.validator.GetParameterValidator().ValidatePathParams(request)
	if len(errs) > 0 {
		for _, err := range errs {
			fmt.Println(err)
		}

		return fmt.Errorf("request is not valid: %v", errs)
	}

	if !valid {
		return fmt.Errorf("request is not valid")
	}

	return nil
}
```

Could you please provide guidance on whether it is possible to use a regex to validate path parameters in the specified manner? If so, could you kindly point out any potential mistakes or provide alternative solutions?
