### ISSUE TITLE
Validation of simple parameters

### ISSUE THREAD

**Issue by tksd123** [pb33f/libopenapi-validator#54]
Hi there, I think I'm facing an issue with validation.

Example like the following:

```yaml
- in: query
  name: count
  description: number of facts to return
  required: false
  schema:
    type: integer
    format: int32
    minimum: 1
```

There is no check on the minimum value in that case with simple schema having a primitive type like integer.

When it is working with:

```yaml
ListSpacesPage:
  name: "page"
  in: "query"
  style: "deepObject"
  description: "list spaces paginated request"
  required: false
  schema:
    type: object
    properties:
      size:
        type: integer
        description: The maximum number of items to return. The service may return fewer than this value.
        minimum: 1
        maximum: 50
        default: 30
        format: int32
        require: false
```

Is this by design, a bug, or I'm missing something?

Cheers and thank you for this amazing lib and the work you're putting in.
