### ISSUE TITLE
Handling of default values in query parameters

### ISSUE THREAD

**Issue by emilien-puget** [pb33f/libopenapi-validator#56]
First of all, i love what you did there.

What do you think about handling default values in query parameters ?

**Comment by daveshanley** [comment]
Could you help me understand a little more?

**Comment by emilien-puget** [comment]
in a open api specification, a default value can be specified like so

```yaml
      name: "page"
      in: "query"
      style: "deepObject"
      required: false
      schema:
        type: object
        properties:
          size:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
            require: false
```

Right now we would reject an http query with `size` not set because it violates the schema, but a default value is set.
