### ISSUE TITLE
OpenAPI 3.0.1 : path parameter validation does not comply the required schema  

### ISSUE THREAD

**Issue by triptesh1212** [pb33f/libopenapi-validator#78]
Hi, I have the following schema defined.

```
paths:
  '/path123/{name}':
    get:
      description: Obtain information about a country from unique country name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
            minLength: 3
``` 

(1) <host>/path123/de path gives the following error which is expected.

"Path /path123/de is invalid or not supported"

(2) **However if we pass empty path parameter <host>/path123/   it passes and does not the return error**
