### ISSUE TITLE
Nested object schema validation in query params

### ISSUE THREAD

**Issue by hendrikheil** [pb33f/libopenapi-validator#83]
Given my understanding of JSON schema and OpenAPI (3.1) the following schema is supposed to be valid:

```yaml
paths:
  /path:
    get:
      parameters:
        - name: obj
          in: query
          style: deepObject
          schema:
            type: object
            properties:
              root:
                type: string
              nested:
                type: object
                properties:
                  child:
                    type: string
          required: true
```

Meaning an URL like `/path?obj[root]=test1&obj[nested][child]=test2` should pass the validation against the schema above.

As far as I can tell from the code deepObject style query parameters are decoded to a flat map of QueryParam arrays. This works for objects with a depth of one, but won't work for objects with more depth.

**Comment by hendrikheil** [comment]
Since this type of notation isn't really standardized anywhere, I think this behavior is generally not an issue.

OpenAPI 3.1 makes no remarks about the level of nesting, where as 3.0 does specify only a single level of nesting.
But in general, there is an ongoing discussion: https://github.com/OAI/OpenAPI-Specification/issues/1706

Since behavior isn't well defined, I think it might still be a good idea to implement the "qs" style of notation, since nested object schemas are generally definable in OAS 3.x.

However, there is a workaround to this issue, which is just flattening the object keys.

```yaml
paths:
  /path:
    get:
      parameters:
        - name: obj
          in: query
          style: deepObject
          schema:
            type: object
            properties:
              root:
                type: string
              nested[child]:
                type: string
          required: true
```

I don't think it has the exact same semantics and definitely doesn't allow as fine grained of a control as one would have with using object type schemas, but I think it is decent enough for a lot of cases.

@daveshanley What do you think about this? Worth keeping it open or should this be closed and the behavior stay as is?
