### ISSUE TITLE
`minLength` still enforced on non-required requestBody

### ISSUE THREAD

**Issue by AidanWelch** [pb33f/libopenapi-validator#99]
For example

```yml
content:
  application/json:
    schema:
      type: object
      properties:
        email:
          type: string
          format: email
          minLength: 3
          maxLength: 254
          example: johndoe@example.com
        name:
          description: User's name
          type: string
          minLength: 1
          maxLength: 30
      required:
        - email
```

will error if name is not provided, because `minLength` isn't met.  The same isn't true for `maxLength`
